name: CI

# Trigger the workflow on push or pull request
on:
  - push
  - pull_request

jobs:
  # The CI test job
  test:
    name: ${{ matrix.gap-branch }} - HPCGAP ${{ matrix.HPCGAP }}
    runs-on: ubuntu-latest
    container:
      image: gapsystem/gap-docker

    steps:
      - uses: actions/checkout@v2
      - uses: gap-actions/setup-gap-for-packages@v1
      - uses: gap-actions/run-test-for-packages@v1
